Repository jenkinsci/declarative-pipeline-migration-assistant-plugin, pull requests merged in 2023-02, with the labels that each got.

#168 Add Java 17 to build/test matrix
  Jenkinsfile
  declarative-pipeline-migration-assistant/src/test/resources/maven3-project.zip
Labels: maintenance

#169 improve testing of ansiColor converter
  declarative-pipeline-migration-assistant/src/test/java/io/jenkins/plugins/todeclarative/converter/FreestyleTest.java
Labels: test

#173 add Maven build cache extension setup
  .mvn/extensions.xml
Labels: maintenance

#177 comment maven-build-cache-extension as it's not a good idea (yet..)
  .mvn/extensions.xml
Labels: skip-changelog
